### ISSUE TITLE
Trac: #326 SST Workbench: Add support for property units, limits and datatypes

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-workbench#23]
Currently all property input is string data with no check on data types or limits. Add support for properties to control user entry of units, limits and data types. This would reduce user data input errors. NOTE: In order to implement this feature, a major feature change to the ElementInfoParam object would have to be made to support this info. Additionally, all components would have to be updated to provide this information.

**Comment by allevin** [comment]
Redundant entry
