### ISSUE TITLE
Trac: #386 SST Workbench: Does not tolerate additional elements to SSTInfo.xml

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-workbench#24]
For SST 5.0, the elementinfo structures changed to support statistics and subcomponents. If the sstinfo generates appropriate XML elements in SSTInfo.xml for these new structures, the SSTWorkbench will not import the SSTInfo.xml properly. Currently for 5.0, the sstinfo will not modify its xml format. This is not an issue as the SSTWorkbench does not use any of this new data.

**Comment by allevin** [comment]
Redundant entry
